export enum SuiAction {
    TRANSFER_TOKEN = "TRANSFER_TOKEN",
    SWAP_TOKEN = "SWAP_TOKEN",
    GET_BALANCE = "GET_BALANCE",
    GET_TOKEN = "GET_TOKEN",
    GET_PORTFOLIO = "GET_PORTFOLIO",
}

export enum SuiLendAction {
    BORROW_TOKEN_SUILEND = "BORROW_TOKEN_SUILEND",
    REPAY_TOKEN_SUILEND = "REPAY_TOKEN_SUILEND",
    DEPOSIT_TOKEN_SUILEND = "DEPOSIT_TOKEN_SUILEND",
    WITHDRAW_TOKEN_SUILEND = "WITHDRAW_TOKEN_SUILEND",
}
